-- Table TBL_ANNONCE
CREATE TABLE TBL_ANNONCE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  titre VARCHAR(255) NOT NULL,
  description TEXT,
  prix DECIMAL(10,2) NOT NULL,
  type_annonce INT NOT NULL,
  sold BOOLEAN DEFAULT 0,
  image_url VARCHAR(255) NOT NULL,
  client_id INT NOT NULL,
  pays_id INT NOT NULL,
  ville_id INT NOT NULL,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES TBL_CLIENT(id),
  FOREIGN KEY (pays_id) REFERENCES TBL_PAYS(id),
  FOREIGN KEY (ville_id) REFERENCES TBL_VILLE(id)
);