-- Table TBL_CLIENT
CREATE TABLE TBL_CLIENT (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  pays_id INT NOT NULL,
  ville_id INT NOT NULL,
  optin TIMESTAMP
);