-- Table TBL_VILLE
CREATE TABLE TBL_VILLE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(100) NOT NULL,
  code_postal VARCHAR(10) NOT NULL,
  pays_id INT NOT NULL,
  FOREIGN KEY (pays_id) REFERENCES TBL_PAYS(id)
);




